"""Add daily silo balance table

Revision ID: 117f25e150a7
Revises: 5636af4e53a8
Create Date: 2026-01-12 23:01:50.513960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117f25e150a7'
down_revision = '5636af4e53a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_silo_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('silo_id', sa.Integer(), nullable=False),
    sa.Column('opening_stock', sa.Float(), nullable=False),
    sa.Column('inflow_mt', sa.Float(), nullable=False),
    sa.Column('dispatched_mt', sa.Float(), nullable=False),
    sa.Column('closing_stock', sa.Float(), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('day_closed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['silo_id'], ['silo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'silo_id', name='uq_date_silo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_silo_balance')
    # ### end Alembic commands ###
