"""Add silo_id and party_id to trip

Revision ID: 2d4590949358
Revises: 0de96b794dc1
Create Date: 2026-01-12 22:36:01.762354

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2d4590949358"
down_revision = "0de96b794dc1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trip", schema=None) as batch_op:
        batch_op.add_column(sa.Column("silo_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("party_id", sa.Integer(), nullable=True))
        batch_op.alter_column(
            "gate_in_time", existing_type=sa.DATETIME(), nullable=True
        )
        batch_op.create_foreign_key("fk_trip_silo_id", "silo", ["silo_id"], ["id"])
        batch_op.create_foreign_key("fk_trip_party_id", "party", ["party_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trip", schema=None) as batch_op:
        batch_op.drop_constraint("fk_trip_silo_id", type_="foreignkey")
        batch_op.drop_constraint("fk_trip_party_id", type_="foreignkey")
        batch_op.alter_column(
            "gate_in_time", existing_type=sa.DATETIME(), nullable=False
        )
        batch_op.drop_column("party_id")
        batch_op.drop_column("silo_id")

    # ### end Alembic commands ###
