"""Add silo inflow table

Revision ID: 5636af4e53a8
Revises: 2d4590949358
Create Date: 2026-01-12 22:58:45.500585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5636af4e53a8'
down_revision = '2d4590949358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('silo_inflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('silo_id', sa.Integer(), nullable=False),
    sa.Column('quantity_mt', sa.Float(), nullable=False),
    sa.Column('inflow_time', sa.DateTime(), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['silo_id'], ['silo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('silo_inflow')
    # ### end Alembic commands ###
