"""add weighbridge fields to trip

Revision ID: 67e17f7593ac
Revises: c73dbb58a2a8
Create Date: 2026-01-07 00:20:26.705352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e17f7593ac'
down_revision = 'c73dbb58a2a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empty_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('loaded_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ash_quantity', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('ash_quantity')
        batch_op.drop_column('loaded_weight')
        batch_op.drop_column('empty_weight')

    # ### end Alembic commands ###
