"""Add qr_image_path to truck

Revision ID: 8f42ed1e17f1
Revises: 117f25e150a7
Create Date: 2026-01-16 00:46:31.720771

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8f42ed1e17f1"
down_revision = "117f25e150a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("truck", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("qr_image_path", sa.String(length=255), nullable=True)
        )
        batch_op.alter_column(
            "qr_code",
            existing_type=sa.VARCHAR(length=200),
            type_=sa.String(length=100),
            existing_nullable=True,
        )
        batch_op.create_unique_constraint("uq_truck_qr_code", ["qr_code"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("truck", schema=None) as batch_op:
        batch_op.drop_constraint("qr_image_path", type_="unique")
        batch_op.alter_column(
            "qr_code",
            existing_type=sa.String(length=100),
            type_=sa.VARCHAR(length=200),
            existing_nullable=True,
        )
        batch_op.drop_column("qr_image_path")

    # ### end Alembic commands ###
