"""Add trip_type, status, remarks to trip

Revision ID: 901cbc7df566
Revises: 67e17f7593ac
Create Date: 2026-01-08 00:17:47.318192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901cbc7df566'
down_revision = '67e17f7593ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('remarks')
        batch_op.drop_column('status')
        batch_op.drop_column('trip_type')

    # ### end Alembic commands ###
