"""create trip table

Revision ID: c73dbb58a2a8
Revises: 3749fc76d4f8
Create Date: 2026-01-07 00:00:47.863412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73dbb58a2a8'
down_revision = '3749fc76d4f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('gate_in_time', sa.DateTime(), nullable=False),
    sa.Column('gate_out_time', sa.DateTime(), nullable=True),
    sa.Column('turnaround_minutes', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['truck_id'], ['truck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip')
    # ### end Alembic commands ###
